run:
  timeout: 5m
  issues-exit-code: 1
  tests: true

output:
  formats:
    - format: colored-line-number

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  govet:
    enable-all: true
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 3
    min-occurrences: 3
  misspell:
    locale: US
  lll:
    line-length: 120
  goimports:
    local-prefixes: github.com/zzszmyf/codefuse
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/zzszmyf/codefuse)

linters:
  enable:
    - bodyclose
    - dogsled
    - dupl
    - errcheck
    - goconst
    - gocyclo
    - gofmt
    - goimports
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace
  disable:
    - maligned  # deprecated, replaced by fieldalignment

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
